"""Offline checks for scripts/upstream_state.py and the snapshot it writes.

No network, no venv, no reference clone: the extractor is exercised against a
fixture cascade tree built in a temp dir, and the committed snapshot is checked
for the properties the prose pins in test_stale_references.py rely on.
"""

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from unittest import TestCase

from scripts import upstream_state as us

ROOT = Path(__file__).resolve().parents[1]

FIXTURE_CHAIN = """
schema_version = 1

[subnet]
netuid = 91

[round]
finalists = 2
heat_n_windows = 2000

[scoring]
cascade_enabled = true
cascade_top_k = 3

[dependencies]
allowed = ["numpy", "scipy"]
"""

FIXTURE_DECISION = """---
id: DEC-CA-0099
type: decision
title: "A decision whose title has a | pipe in it"
status: active
date: 2026-08-16
relations: {depends_on: DEC-CA-0013}
---
Body text, not parsed.
"""


class ExtractorTests(TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.cascade = Path(self.tmp.name)
        (self.cascade / "chain.toml").write_text(FIXTURE_CHAIN)
        (self.cascade / "decisions").mkdir()
        (self.cascade / "decisions/DEC-CA-0099-example.md").write_text(FIXTURE_DECISION)
        self.addCleanup(self.tmp.cleanup)

    def test_tracked_keys_are_extracted_with_their_types(self):
        state = us.build(self.cascade)
        self.assertEqual(state["keys"]["subnet.netuid"], 91)
        self.assertEqual(state["keys"]["round.finalists"], 2)
        self.assertIs(state["keys"]["scoring.cascade_enabled"], True)
        self.assertEqual(state["keys"]["dependencies.allowed"], ["numpy", "scipy"])

    def test_a_key_that_vanishes_upstream_is_reported_not_fatal(self):
        # A renamed or removed key is a change we must SEE, so it lands in
        # missing_keys rather than crashing the sync or silently disappearing.
        state = us.build(self.cascade)
        self.assertIn("training.target_train_hours", state["missing_keys"])
        self.assertNotIn("training.target_train_hours", state["keys"])

    def test_decision_frontmatter_is_read(self):
        [decision] = us.build(self.cascade)["decisions"]
        self.assertEqual(decision["id"], "DEC-CA-0099")
        self.assertEqual(decision["status"], "active")
        self.assertEqual(decision["date"], "2026-08-16")
        self.assertIn("pipe in it", decision["title"])

    def test_missing_chain_toml_is_an_actionable_error(self):
        with tempfile.TemporaryDirectory() as empty:
            with self.assertRaisesRegex(us.ExtractError, "CASCADE_DIR"):
                us.build(Path(empty))

    def test_rendered_table_escapes_pipes(self):
        # A bare `|` inside a title or value would split the row into extra
        # columns and quietly mangle the table.
        rendered = us.render(us.build(self.cascade))
        for line in rendered.splitlines():
            if line.startswith("| `DEC-CA-0099`"):
                self.assertIn("\\|", line)
                self.assertEqual(len(re.findall(r"(?<!\\)\|", line)), 5, line)
                break
        else:
            self.fail("decision row missing from the rendered table")

    def test_render_marks_the_file_as_generated(self):
        self.assertIn("GENERATED by scripts/upstream_state.py", us.render(us.build(self.cascade)))


class CliTests(TestCase):
    def run_cli(self, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            [sys.executable, str(ROOT / "scripts/upstream_state.py"), *args],
            capture_output=True, text=True,
        )

    def test_check_reports_drift_without_writing(self):
        with tempfile.TemporaryDirectory() as tmp:
            (Path(tmp) / "chain.toml").write_text(FIXTURE_CHAIN)
            before = us.SNAPSHOT.read_bytes()
            result = self.run_cli("--cascade-dir", tmp, "--check")
            self.assertEqual(result.returncode, us.EXIT_DRIFT, result.stdout + result.stderr)
            self.assertIn("STALE", result.stdout)
            # names the keys that moved, so a cron alert is actionable on its own
            self.assertIn("round.finalists", result.stdout)
            self.assertEqual(us.SNAPSHOT.read_bytes(), before)

    def test_print_writes_nothing_to_the_repo(self):
        with tempfile.TemporaryDirectory() as tmp:
            (Path(tmp) / "chain.toml").write_text(FIXTURE_CHAIN)
            before = us.SNAPSHOT.read_bytes()
            result = self.run_cli("--cascade-dir", tmp, "--print")
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(json.loads(result.stdout)["keys"]["subnet.netuid"], 91)
            self.assertEqual(us.SNAPSHOT.read_bytes(), before)

    def test_missing_clone_exits_one_with_a_pointer(self):
        result = self.run_cli("--cascade-dir", "/nonexistent/cascade")
        self.assertEqual(result.returncode, 1)
        self.assertIn("CASCADE_DIR", result.stderr)


class CommittedSnapshotTests(TestCase):
    def setUp(self):
        self.state = us.load_snapshot()

    def test_snapshot_is_current_schema_and_names_its_source(self):
        self.assertEqual(self.state["schema"], us.SCHEMA)
        self.assertEqual(self.state["generated_from"]["repo"], us.UPSTREAM_REPO)
        self.assertNotEqual(self.state["generated_from"]["revision"], "unknown")

    def test_every_tracked_key_is_present(self):
        # A tracked key missing from the snapshot means upstream renamed or
        # dropped it — the sync PR should not be merged until we know which.
        self.assertEqual(self.state["missing_keys"], [], "keys vanished upstream")
        for _group, dotted, _why in us.KEYS:
            self.assertIn(dotted, self.state["keys"])

    def test_rendered_table_matches_the_json(self):
        # The two files are written together; a hand-edit to either shows up here.
        self.assertEqual(us.RENDERED.read_text(encoding="utf-8"), us.render(self.state))

    def test_decisions_are_recorded(self):
        ids = {d["id"] for d in self.state["decisions"]}
        self.assertIn("DEC-CA-0009", ids)   # the live metric
        self.assertIn("DEC-CA-0013", ids)   # warm-start promotion
